FROM debian:bullseye

RUN apt update && apt install -y asterisk asterisk-dev

# Limpar módulos problemáticos
#RUN find /usr/lib/asterisk/modules -name "*stasis*" -delete && \
#    find /usr/lib/asterisk/modules -name "*ari*" -delete && \
#    find /usr/lib/asterisk/modules -name "*websocket*" -delete

# Expor portas
EXPOSE 5038 5060/udp

# Iniciar
CMD ["asterisk", "-f", "-vvv"]
